// Code generated by protoc-gen-go.
// source: kv.proto
// DO NOT EDIT!

/*
Package kv is a generated protocol buffer package.

It is generated from these files:
	kv.proto

It has these top-level messages:
	Data
	SetRequest
	GetRequest
	SetReply
	GetReply
	Dataset
	MirrorRequest
	MirrorResponse
	SyncServerRequest
	SyncServerReply
	ServerInfo
	AddServerRequest
	AddServerReply
	AddDatasetRequest
	AddDatasetReply
	DelDatasetRequest
	DelDatasetReply
*/
package kv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Sequence int64  `protobuf:"varint,1,opt,name=Sequence" json:"Sequence,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The request message containing the user's name.
type SetRequest struct {
	Dataset string `protobuf:"bytes,1,opt,name=Dataset" json:"Dataset,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value   []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetRequest struct {
	Dataset string `protobuf:"bytes,1,opt,name=Dataset" json:"Dataset,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// The response message containing the greetings
type SetReply struct {
	Sequence int64 `protobuf:"varint,1,opt,name=Sequence" json:"Sequence,omitempty"`
}

func (m *SetReply) Reset()                    { *m = SetReply{} }
func (m *SetReply) String() string            { return proto.CompactTextString(m) }
func (*SetReply) ProtoMessage()               {}
func (*SetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetReply struct {
	Data *Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetReply) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Dataset struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Sequence int64  `protobuf:"varint,2,opt,name=Sequence" json:"Sequence,omitempty"`
}

func (m *Dataset) Reset()                    { *m = Dataset{} }
func (m *Dataset) String() string            { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()               {}
func (*Dataset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type MirrorRequest struct {
	Cmd     string   `protobuf:"bytes,1,opt,name=Cmd" json:"Cmd,omitempty"`
	Addr    string   `protobuf:"bytes,2,opt,name=Addr" json:"Addr,omitempty"`
	Dataset *Dataset `protobuf:"bytes,3,opt,name=Dataset" json:"Dataset,omitempty"`
}

func (m *MirrorRequest) Reset()                    { *m = MirrorRequest{} }
func (m *MirrorRequest) String() string            { return proto.CompactTextString(m) }
func (*MirrorRequest) ProtoMessage()               {}
func (*MirrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MirrorRequest) GetDataset() *Dataset {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type MirrorResponse struct {
	Cmd     string   `protobuf:"bytes,1,opt,name=Cmd" json:"Cmd,omitempty"`
	Dataset string   `protobuf:"bytes,2,opt,name=Dataset" json:"Dataset,omitempty"`
	Args    []string `protobuf:"bytes,3,rep,name=Args" json:"Args,omitempty"`
	Data    *Data    `protobuf:"bytes,4,opt,name=Data" json:"Data,omitempty"`
}

func (m *MirrorResponse) Reset()                    { *m = MirrorResponse{} }
func (m *MirrorResponse) String() string            { return proto.CompactTextString(m) }
func (*MirrorResponse) ProtoMessage()               {}
func (*MirrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MirrorResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncServerRequest struct {
	Dataset map[string]int64 `protobuf:"bytes,1,rep,name=Dataset" json:"Dataset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *SyncServerRequest) Reset()                    { *m = SyncServerRequest{} }
func (m *SyncServerRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncServerRequest) ProtoMessage()               {}
func (*SyncServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SyncServerRequest) GetDataset() map[string]int64 {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type SyncServerReply struct {
	Server map[string]*ServerInfo `protobuf:"bytes,1,rep,name=Server" json:"Server,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SyncServerReply) Reset()                    { *m = SyncServerReply{} }
func (m *SyncServerReply) String() string            { return proto.CompactTextString(m) }
func (*SyncServerReply) ProtoMessage()               {}
func (*SyncServerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SyncServerReply) GetServer() map[string]*ServerInfo {
	if m != nil {
		return m.Server
	}
	return nil
}

type ServerInfo struct {
	ServerId string            `protobuf:"bytes,1,opt,name=ServerId" json:"ServerId,omitempty"`
	Version  int64             `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	Addr     string            `protobuf:"bytes,3,opt,name=Addr" json:"Addr,omitempty"`
	Dataset  map[string]string `protobuf:"bytes,4,rep,name=Dataset" json:"Dataset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ServerInfo) GetDataset() map[string]string {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type AddServerRequest struct {
}

func (m *AddServerRequest) Reset()                    { *m = AddServerRequest{} }
func (m *AddServerRequest) String() string            { return proto.CompactTextString(m) }
func (*AddServerRequest) ProtoMessage()               {}
func (*AddServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type AddServerReply struct {
}

func (m *AddServerReply) Reset()                    { *m = AddServerReply{} }
func (m *AddServerReply) String() string            { return proto.CompactTextString(m) }
func (*AddServerReply) ProtoMessage()               {}
func (*AddServerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type AddDatasetRequest struct {
	ServerId string `protobuf:"bytes,1,opt,name=ServerId" json:"ServerId,omitempty"`
	Dataset  string `protobuf:"bytes,2,opt,name=Dataset" json:"Dataset,omitempty"`
}

func (m *AddDatasetRequest) Reset()                    { *m = AddDatasetRequest{} }
func (m *AddDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*AddDatasetRequest) ProtoMessage()               {}
func (*AddDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type AddDatasetReply struct {
}

func (m *AddDatasetReply) Reset()                    { *m = AddDatasetReply{} }
func (m *AddDatasetReply) String() string            { return proto.CompactTextString(m) }
func (*AddDatasetReply) ProtoMessage()               {}
func (*AddDatasetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type DelDatasetRequest struct {
	ServerId string `protobuf:"bytes,1,opt,name=ServerId" json:"ServerId,omitempty"`
	Dataset  string `protobuf:"bytes,2,opt,name=Dataset" json:"Dataset,omitempty"`
}

func (m *DelDatasetRequest) Reset()                    { *m = DelDatasetRequest{} }
func (m *DelDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*DelDatasetRequest) ProtoMessage()               {}
func (*DelDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type DelDatasetReply struct {
	ServerId string `protobuf:"bytes,1,opt,name=ServerId" json:"ServerId,omitempty"`
}

func (m *DelDatasetReply) Reset()                    { *m = DelDatasetReply{} }
func (m *DelDatasetReply) String() string            { return proto.CompactTextString(m) }
func (*DelDatasetReply) ProtoMessage()               {}
func (*DelDatasetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*Data)(nil), "kv.Data")
	proto.RegisterType((*SetRequest)(nil), "kv.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "kv.GetRequest")
	proto.RegisterType((*SetReply)(nil), "kv.SetReply")
	proto.RegisterType((*GetReply)(nil), "kv.GetReply")
	proto.RegisterType((*Dataset)(nil), "kv.Dataset")
	proto.RegisterType((*MirrorRequest)(nil), "kv.MirrorRequest")
	proto.RegisterType((*MirrorResponse)(nil), "kv.MirrorResponse")
	proto.RegisterType((*SyncServerRequest)(nil), "kv.SyncServerRequest")
	proto.RegisterType((*SyncServerReply)(nil), "kv.SyncServerReply")
	proto.RegisterType((*ServerInfo)(nil), "kv.ServerInfo")
	proto.RegisterType((*AddServerRequest)(nil), "kv.AddServerRequest")
	proto.RegisterType((*AddServerReply)(nil), "kv.AddServerReply")
	proto.RegisterType((*AddDatasetRequest)(nil), "kv.AddDatasetRequest")
	proto.RegisterType((*AddDatasetReply)(nil), "kv.AddDatasetReply")
	proto.RegisterType((*DelDatasetRequest)(nil), "kv.DelDatasetRequest")
	proto.RegisterType((*DelDatasetReply)(nil), "kv.DelDatasetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Kv service

type KvClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type kvClient struct {
	cc *grpc.ClientConn
}

func NewKvClient(cc *grpc.ClientConn) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error) {
	out := new(SetReply)
	err := grpc.Invoke(ctx, "/kv.Kv/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/kv.Kv/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kv service

type KvServer interface {
	Set(context.Context, *SetRequest) (*SetReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
}

func RegisterKvServer(s *grpc.Server, srv KvServer) {
	s.RegisterService(&_Kv_serviceDesc, srv)
}

func _Kv_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Kv/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Kv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Kv_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Kv_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Mirror service

type MirrorClient interface {
	Mirror(ctx context.Context, opts ...grpc.CallOption) (Mirror_MirrorClient, error)
}

type mirrorClient struct {
	cc *grpc.ClientConn
}

func NewMirrorClient(cc *grpc.ClientConn) MirrorClient {
	return &mirrorClient{cc}
}

func (c *mirrorClient) Mirror(ctx context.Context, opts ...grpc.CallOption) (Mirror_MirrorClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Mirror_serviceDesc.Streams[0], c.cc, "/kv.Mirror/Mirror", opts...)
	if err != nil {
		return nil, err
	}
	x := &mirrorMirrorClient{stream}
	return x, nil
}

type Mirror_MirrorClient interface {
	Send(*MirrorRequest) error
	Recv() (*MirrorResponse, error)
	grpc.ClientStream
}

type mirrorMirrorClient struct {
	grpc.ClientStream
}

func (x *mirrorMirrorClient) Send(m *MirrorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mirrorMirrorClient) Recv() (*MirrorResponse, error) {
	m := new(MirrorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mirror service

type MirrorServer interface {
	Mirror(Mirror_MirrorServer) error
}

func RegisterMirrorServer(s *grpc.Server, srv MirrorServer) {
	s.RegisterService(&_Mirror_serviceDesc, srv)
}

func _Mirror_Mirror_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MirrorServer).Mirror(&mirrorMirrorServer{stream})
}

type Mirror_MirrorServer interface {
	Send(*MirrorResponse) error
	Recv() (*MirrorRequest, error)
	grpc.ServerStream
}

type mirrorMirrorServer struct {
	grpc.ServerStream
}

func (x *mirrorMirrorServer) Send(m *MirrorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mirrorMirrorServer) Recv() (*MirrorRequest, error) {
	m := new(MirrorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Mirror_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.Mirror",
	HandlerType: (*MirrorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Mirror",
			Handler:       _Mirror_Mirror_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

// Client API for Cluster service

type ClusterClient interface {
	AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*AddServerReply, error)
	AddDataset(ctx context.Context, in *AddDatasetRequest, opts ...grpc.CallOption) (*AddDatasetReply, error)
	DelDataset(ctx context.Context, in *DelDatasetRequest, opts ...grpc.CallOption) (*DelDatasetReply, error)
	SyncServer(ctx context.Context, in *SyncServerRequest, opts ...grpc.CallOption) (*SyncServerReply, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*AddServerReply, error) {
	out := new(AddServerReply)
	err := grpc.Invoke(ctx, "/kv.Cluster/AddServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) AddDataset(ctx context.Context, in *AddDatasetRequest, opts ...grpc.CallOption) (*AddDatasetReply, error) {
	out := new(AddDatasetReply)
	err := grpc.Invoke(ctx, "/kv.Cluster/AddDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) DelDataset(ctx context.Context, in *DelDatasetRequest, opts ...grpc.CallOption) (*DelDatasetReply, error) {
	out := new(DelDatasetReply)
	err := grpc.Invoke(ctx, "/kv.Cluster/DelDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) SyncServer(ctx context.Context, in *SyncServerRequest, opts ...grpc.CallOption) (*SyncServerReply, error) {
	out := new(SyncServerReply)
	err := grpc.Invoke(ctx, "/kv.Cluster/SyncServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	AddServer(context.Context, *AddServerRequest) (*AddServerReply, error)
	AddDataset(context.Context, *AddDatasetRequest) (*AddDatasetReply, error)
	DelDataset(context.Context, *DelDatasetRequest) (*DelDatasetReply, error)
	SyncServer(context.Context, *SyncServerRequest) (*SyncServerReply, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_AddServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).AddServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Cluster/AddServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).AddServer(ctx, req.(*AddServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_AddDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).AddDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Cluster/AddDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).AddDataset(ctx, req.(*AddDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_DelDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).DelDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Cluster/DelDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).DelDataset(ctx, req.(*DelDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_SyncServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).SyncServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.Cluster/SyncServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).SyncServer(ctx, req.(*SyncServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddServer",
			Handler:    _Cluster_AddServer_Handler,
		},
		{
			MethodName: "AddDataset",
			Handler:    _Cluster_AddDataset_Handler,
		},
		{
			MethodName: "DelDataset",
			Handler:    _Cluster_DelDataset_Handler,
		},
		{
			MethodName: "SyncServer",
			Handler:    _Cluster_SyncServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("kv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x8b, 0x13, 0x4d,
	0x10, 0xce, 0xcc, 0xe4, 0xcd, 0x26, 0x95, 0xbc, 0xf9, 0x68, 0x57, 0x08, 0xa3, 0xa0, 0x34, 0x2a,
	0xb9, 0x18, 0x24, 0x22, 0xae, 0x41, 0x10, 0xd9, 0x95, 0x10, 0x17, 0xf7, 0x30, 0x81, 0x3d, 0x79,
	0x89, 0x9b, 0x56, 0x96, 0x64, 0x67, 0x62, 0xcf, 0x24, 0x90, 0x1f, 0xe1, 0xd1, 0x1f, 0xe5, 0x1f,
	0xf2, 0x6c, 0x57, 0x7f, 0x4d, 0xcf, 0x24, 0xa8, 0xc8, 0x5e, 0x42, 0x57, 0x4d, 0x3d, 0x4f, 0x3d,
	0xf5, 0xd1, 0x1d, 0xa8, 0x2f, 0xb7, 0xc3, 0x35, 0x4f, 0xb2, 0x84, 0xf8, 0xcb, 0x2d, 0x7d, 0x0f,
	0xd5, 0xb3, 0x79, 0x36, 0x27, 0x21, 0xd4, 0x67, 0xec, 0xeb, 0x86, 0xc5, 0x57, 0xac, 0xef, 0x3d,
	0xf4, 0x06, 0x41, 0x64, 0x6d, 0xd2, 0x85, 0xe0, 0x9c, 0xed, 0xfa, 0xbe, 0x70, 0xb7, 0x22, 0x3c,
	0x92, 0x63, 0xf8, 0xef, 0x72, 0xbe, 0xda, 0xb0, 0x7e, 0x20, 0x7d, 0xca, 0xa0, 0x17, 0x00, 0x33,
	0x96, 0x45, 0x08, 0x4b, 0x33, 0xd2, 0x87, 0x23, 0x64, 0x4e, 0x59, 0x26, 0x09, 0x1b, 0x91, 0x31,
	0xff, 0x9a, 0xef, 0x04, 0x60, 0xf2, 0x4f, 0x7c, 0xf4, 0x09, 0x56, 0x23, 0x90, 0xeb, 0xd5, 0xee,
	0x77, 0x95, 0xd1, 0x01, 0xd4, 0x27, 0x26, 0xee, 0x3e, 0x54, 0x17, 0x82, 0x50, 0xc6, 0x34, 0x47,
	0xf5, 0xa1, 0x68, 0x13, 0x26, 0x88, 0xa4, 0x97, 0xbe, 0xb2, 0xd9, 0x09, 0x81, 0xea, 0xc5, 0xfc,
	0x86, 0x69, 0x15, 0xf2, 0x5c, 0x48, 0xe2, 0x97, 0x92, 0x7c, 0x84, 0xff, 0x3f, 0x5c, 0x73, 0x9e,
	0x70, 0x53, 0x89, 0xd0, 0x7b, 0x7a, 0xb3, 0xd0, 0x78, 0x3c, 0x22, 0xe5, 0xdb, 0xc5, 0x82, 0x4b,
	0xa8, 0xa0, 0xc4, 0x33, 0x79, 0x9c, 0xd7, 0x1b, 0x48, 0x49, 0x4d, 0x23, 0x49, 0xb8, 0x6c, 0xf1,
	0x34, 0x86, 0xb6, 0x61, 0x4f, 0xd7, 0x49, 0x9c, 0xb2, 0x03, 0xf4, 0x4e, 0xeb, 0xfc, 0x62, 0xeb,
	0x30, 0x31, 0xff, 0x92, 0x8a, 0x0c, 0x81, 0x4c, 0x2c, 0xce, 0xd8, 0x08, 0xfc, 0xdc, 0xaf, 0x96,
	0x1b, 0x81, 0xbf, 0xf4, 0x9b, 0x07, 0xbd, 0xd9, 0x2e, 0xbe, 0x9a, 0x31, 0xbe, 0x65, 0xb6, 0xa4,
	0xd7, 0xee, 0x70, 0x02, 0x01, 0xa3, 0x08, 0xdb, 0x8b, 0x33, 0xf2, 0xdf, 0xc5, 0x19, 0xdf, 0x59,
	0x15, 0xe1, 0x18, 0x5a, 0xee, 0x07, 0xac, 0x60, 0x29, 0x06, 0xaa, 0x2b, 0x58, 0xaa, 0x05, 0xd9,
	0xca, 0x05, 0x51, 0xcd, 0x55, 0xc6, 0xd8, 0x3f, 0xf1, 0xe8, 0x77, 0x0f, 0x3a, 0x6e, 0x1e, 0x1c,
	0xe5, 0x4b, 0xa8, 0x29, 0x53, 0x8b, 0x79, 0x50, 0x16, 0x23, 0x82, 0x86, 0xea, 0xac, 0x94, 0xe8,
	0xf0, 0x70, 0x0a, 0x4d, 0xc7, 0x7d, 0x40, 0xc7, 0x23, 0x57, 0x47, 0x73, 0xd4, 0x96, 0xc4, 0x12,
	0x31, 0x8d, 0x3f, 0x27, 0xae, 0xae, 0x1f, 0x1e, 0xde, 0x06, 0xf3, 0x45, 0x2d, 0x88, 0xb4, 0xcc,
	0x64, 0xac, 0x8d, 0xe3, 0xb9, 0x64, 0x3c, 0xbd, 0x4e, 0x62, 0x5d, 0x9e, 0x31, 0xed, 0x5e, 0x04,
	0xce, 0x5e, 0xbc, 0xc8, 0x5b, 0x5d, 0x95, 0xd5, 0xdd, 0x2b, 0x8a, 0xb8, 0x9d, 0x1e, 0x37, 0xdc,
	0x5a, 0x08, 0x74, 0x45, 0xea, 0xc2, 0x24, 0x69, 0x17, 0xda, 0x8e, 0x4f, 0x34, 0x94, 0x4e, 0xa1,
	0x27, 0x3c, 0x66, 0x41, 0xf5, 0x62, 0xfc, 0xa1, 0xee, 0xc3, 0x6b, 0x49, 0x7b, 0xd0, 0x71, 0xa9,
	0x34, 0xfb, 0x19, 0x5b, 0xdd, 0x0a, 0xfb, 0x53, 0xe8, 0xb8, 0x54, 0xf6, 0x91, 0x38, 0x4c, 0x34,
	0x8a, 0xc0, 0x3f, 0xdf, 0x8a, 0xeb, 0x18, 0x88, 0x27, 0x85, 0xe8, 0x89, 0x1b, 0x05, 0x61, 0xcb,
	0xda, 0x28, 0xb2, 0x82, 0x61, 0x13, 0x13, 0x36, 0x29, 0x85, 0x4d, 0x6c, 0xd8, 0xe8, 0x0d, 0xd4,
	0xd4, 0xad, 0x15, 0xe3, 0x34, 0xa7, 0x1e, 0xc6, 0x14, 0x5e, 0x8a, 0x90, 0xb8, 0x2e, 0x75, 0xbd,
	0x69, 0x65, 0xe0, 0x3d, 0xf3, 0x46, 0x3f, 0x3d, 0x38, 0x3a, 0x5d, 0x6d, 0xd2, 0x8c, 0x71, 0xb1,
	0xee, 0x0d, 0x3b, 0x0a, 0x72, 0x8c, 0x90, 0xf2, 0xb4, 0x14, 0x51, 0x69, 0x5e, 0x15, 0x32, 0x06,
	0xc8, 0xdb, 0x4c, 0xee, 0xea, 0x98, 0x62, 0x8f, 0xc3, 0x3b, 0x65, 0xb7, 0xc5, 0xe6, 0x4d, 0x54,
	0xd8, 0xbd, 0xf9, 0x28, 0x6c, 0xa9, 0xd7, 0x0a, 0x9b, 0xdf, 0x46, 0x85, 0xdd, 0x7b, 0x2a, 0x14,
	0xb6, 0x74, 0x69, 0x69, 0xe5, 0x53, 0x4d, 0xfe, 0x77, 0x3d, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x5b, 0xf2, 0xb2, 0x55, 0xc7, 0x06, 0x00, 0x00,
}
